//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::{
    folders::Entity as Folders, org_users::Entity as OrgUsers,
    organizations::Entity as Organizations, users::Entity as Users,
};
